version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: java_test
    ports:
      - '3306:3306'
  redisdb:
    image: redis:5-alpine
    restart: always
    ports:
      - "6379:6379"
